menu:
  友链: /links
  关于: /about
  标签: /tag
  分类: /category
  归档: /archives

main: /

contact:
  网易云音乐: https://music.163.com/#/user/home?id=93953060
  哔哩哔哩❶: https://space.bilibili.com/1659331844
  哔哩哔哩❷: https://space.bilibili.com/12146395
  Github: https://github.com/Makuraryu
  Twitter: https://twitter.com/pumshang2004
  知乎: https://www.zhihu.com/people/pan-shang-98

projects:
  枕流起始页: http://mr-starter.rth.app


linker:
  枕流起始页:
    links: https://mr-starter.rth.app
    avater: https://cdn.retiehe.com/cached-edfcf8a8b627b6c6d3c07879532d97ea/mr-starter/icon.png
    description: 一个自制的小巧起始页
  



